title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- public
- scripts
- vendor
- logs
- templates
ext:
- go
action:
  before:
  - echo "zzz start"
  after:
  - echo "zzz end"
link: https://github.com/midoks/zzz
