// Code generated by re2c 2.2, DO NOT EDIT.
package main

import (
	"fmt"
)

//STATE
const (
	yyc_INITIAL = 0
	yyc_ST_IN_SCRIPTING = 1
)

//TOKEN
const (
	T_EXIT = iota
	T_OPEN_TAG = iota
	T_CLOSE_TAG = iota
	T_ECHO = iota
)



func main(){
	input := "<?php echo '123'; exit;?>\n"
	lex_scan(input)
}

func YYDEBUG(s uint64, c byte){
	fmt.Println(s,string(c))
}

func SCNG(yyvar interface{}) int64{
	fmt.Println(yyvar)
	return 0
}

func lex_scan(zendlval string) int64 {

var token int64
var offset uint64

var yyleng uint64
YYCursor := &LanguageScannerGlobals.YYCursor
YYState := &LanguageScannerGlobals.YYState
YYText := &LanguageScannerGlobals.YYText
restart:
	LanguageScannerGlobals.YYText = *YYCursor;


{
	var yych byte
	if (*YYState < 1) {
		goto yyc_ST_IN_SCRIPTING
	} else {
		goto yyc_INITIAL
	}
/* *********************************** */
yyc_ST_IN_SCRIPTING:
	yych = zendlval[*YYCursor]
	YYDEBUG(*YYCursor, yych)
	if (yych <= 'D') {
		if (yych == '?') {
			goto yy3
		}
	} else {
		if (yych <= 'E') {
			goto yy4
		}
		if (yych == 'e') {
			goto yy4
		}
	}
yy2:
yy3:
	*YYCursor += 1
	yych = zendlval[*YYCursor]
	YYDEBUG(*YYCursor, yych)
	if (yych == '>') {
		goto yy5
	}
	goto yy2
yy4:
	*YYCursor += 1
	yych = zendlval[*YYCursor]
	YYDEBUG(*YYCursor, yych)
	if (yych <= 'X') {
		if (yych == 'C') {
			goto yy7
		}
		if (yych <= 'W') {
			goto yy2
		}
		goto yy8
	} else {
		if (yych <= 'c') {
			if (yych <= 'b') {
				goto yy2
			}
			goto yy7
		} else {
			if (yych == 'x') {
				goto yy8
			}
			goto yy2
		}
	}
yy5:
	*YYCursor += 1
	yych = zendlval[*YYCursor]
	YYDEBUG(*YYCursor, yych)
	if (yych == '\n') {
		goto yy9
	}
	if (yych == '\r') {
		goto yy10
	}
yy6:
	yyleng = *YYCursor - *YYText
	{
	BEGIN(yyc_INITIAL);
	token = T_CLOSE_TAG
	fmt.Println(yyleng,*YYCursor)
	fmt.Println("T_CLOSE_TAG - ?>")
	goto restart
}
yy7:
	*YYCursor += 1
	yych = zendlval[*YYCursor]
	YYDEBUG(*YYCursor, yych)
	if (yych == 'H') {
		goto yy11
	}
	if (yych == 'h') {
		goto yy11
	}
	goto yy2
yy8:
	*YYCursor += 1
	yych = zendlval[*YYCursor]
	YYDEBUG(*YYCursor, yych)
	if (yych == 'I') {
		goto yy12
	}
	if (yych == 'i') {
		goto yy12
	}
	goto yy2
yy9:
	*YYCursor += 1
	goto yy6
yy10:
	*YYCursor += 1
	yych = zendlval[*YYCursor]
	YYDEBUG(*YYCursor, yych)
	if (yych == '\n') {
		goto yy9
	}
	goto yy6
yy11:
	*YYCursor += 1
	yych = zendlval[*YYCursor]
	YYDEBUG(*YYCursor, yych)
	if (yych == 'O') {
		goto yy13
	}
	if (yych == 'o') {
		goto yy13
	}
	goto yy2
yy12:
	*YYCursor += 1
	yych = zendlval[*YYCursor]
	YYDEBUG(*YYCursor, yych)
	if (yych == 'T') {
		goto yy15
	}
	if (yych == 't') {
		goto yy15
	}
	goto yy2
yy13:
	*YYCursor += 1
	yyleng = *YYCursor - *YYText
	{
	token = T_CLOSE_TAG
	fmt.Println("echo")
	fmt.Println(token,offset,yyleng,*YYCursor)
}
yy15:
	*YYCursor += 1
	yyleng = *YYCursor - *YYText
	{
	token = T_EXIT
	fmt.Println("exit")
	fmt.Println(token,offset,yyleng,*YYCursor)
	
}
/* *********************************** */
yyc_INITIAL:
	yych = zendlval[*YYCursor]
	YYDEBUG(*YYCursor, yych)
	if (yych == '<') {
		goto yy20
	}
yy19:
yy20:
	*YYCursor += 1
	yych = zendlval[*YYCursor]
	YYDEBUG(*YYCursor, yych)
	if (yych != '?') {
		goto yy19
	}
	*YYCursor += 1
	yych = zendlval[*YYCursor]
	YYDEBUG(*YYCursor, yych)
	if (yych == 'P') {
		goto yy22
	}
	if (yych != 'p') {
		goto yy19
	}
yy22:
	*YYCursor += 1
	yych = zendlval[*YYCursor]
	YYDEBUG(*YYCursor, yych)
	if (yych == 'H') {
		goto yy23
	}
	if (yych != 'h') {
		goto yy19
	}
yy23:
	*YYCursor += 1
	yych = zendlval[*YYCursor]
	YYDEBUG(*YYCursor, yych)
	if (yych == 'P') {
		goto yy24
	}
	if (yych != 'p') {
		goto yy19
	}
yy24:
	*YYCursor += 1
	yyleng = *YYCursor - *YYText
	{
	BEGIN(yyc_ST_IN_SCRIPTING)
	token = T_OPEN_TAG
	fmt.Println("<?php")
	fmt.Println(token,offset,yyleng,*YYCursor)
	goto emit_token_with_ident
}
}


emit_token_with_ident:
	return token;

}